In [1]:
import pandas as pd

voter = "Data/ge15_2022.csv"

df = pd.read_csv(voter)
print(df.shape)   # (864425, 11)
print(df.dtypes)
df.head(5)

/var/folders/0q/tgbtb0kx7pnbpnvk5m7jqxq80000gn/T/ipykernel_88113/3540866603.py:5: DtypeWarning: Columns (0: dun) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(voter)

(21173638, 11)
uid             str
birth_year    int64
sex             str
ethnicity       str
state           str
parlimen        str
dun             str
dm_vr           str
dm              str
pm              str
saluran       int64
dtype: object

,uid,birth_year,sex,ethnicity,state,parlimen,dun,dm_vr,dm,pm,saluran
0,PVRSJFKCKW,1962,Male,Malay,Perlis,P.001 PADANG BESAR,N01 TITI TINGGI,001/01/05 Padang Besar,001/01/00 Undi Awal,"De-Stress Room, Ibu Pejabat Polis Daerah Padan...",1
1,ASPQJUIBHX,1963,Male,Malay,Perlis,P.001 PADANG BESAR,N01 TITI TINGGI,001/01/05 Padang Besar,001/01/00 Undi Awal,"De-Stress Room, Ibu Pejabat Polis Daerah Padan...",1
2,BTWJTLWOJJ,1963,Male,Malay,Perlis,P.001 PADANG BESAR,N01 TITI TINGGI,001/01/05 Padang Besar,001/01/00 Undi Awal,"De-Stress Room, Ibu Pejabat Polis Daerah Padan...",1
3,TJBHNFHGUZ,1964,Male,Malay,Perlis,P.001 PADANG BESAR,N01 TITI TINGGI,001/01/05 Padang Besar,001/01/00 Undi Awal,"De-Stress Room, Ibu Pejabat Polis Daerah Padan...",1
4,SMIPOTRSZW,1964,Male,Malay,Perlis,P.001 PADANG BESAR,N01 TITI TINGGI,001/01/05 Padang Besar,001/01/00 Undi Awal,"De-Stress Room, Ibu Pejabat Polis Daerah Padan...",1

In [2]:
results = "Data/ns_ge2022_results.csv"

df2 = pd.read_csv(results)
print(df2.shape)   # (864425, 11)
print(df2.dtypes)
df2.head(5)

(1669, 17)
PARLIMEN                                                   str
DUN                                                        str
NO. KOD DAERAH MENGUNDI                                    str
NAMA PUSAT MENGUNDI                                        str
SALURAN                                                float64
KERTAS UNDI DALAM PETI UNDI (A)                          int64
BN                                                       int64
PH                                                       int64
PN                                                       int64
PEJUANG                                                  int64
WARISAN                                                  int64
PSM                                                      int64
IND                                                      int64
IND.1                                                    int64
JUMLAH UNDI                                              int64
UNDI YANG DITOLAK (C)                                    int64
KERTAS UNDI TIDAK DIMASUKKAN KE DALAM PETI UNDI (D)      int64
dtype: object

,PARLIMEN,DUN,NO. KOD DAERAH MENGUNDI,NAMA PUSAT MENGUNDI,SALURAN,KERTAS UNDI DALAM PETI UNDI (A),BN,PH,PN,PEJUANG,WARISAN,PSM,IND,IND.1,JUMLAH UNDI,UNDI YANG DITOLAK (C),KERTAS UNDI TIDAK DIMASUKKAN KE DALAM PETI UNDI (D)
0,P.126 JELEBU,NaN,UNDI POS,NaN,NaN,1245,599,168,299,5,0,0,0,0,1071,75,99
1,P.126 JELEBU,N01 CHENNAH,UNDI AWAL 126/01/00,"KHEMAH A, IPD JELEBU (DUN CHENNAH)",1.0,21,17,0,4,0,0,0,0,0,21,0,0
2,P.126 JELEBU,N02 PERTANG,UNDI AWAL 126/02/00,"KHEMAH B, IPD JELEBU (DUN PERTANG)",1.0,13,9,1,3,0,0,0,0,0,13,0,0
3,P.126 JELEBU,N03 SUNGAI LUI,UNDI AWAL 126/03/00,DEWAN PERDANA PULAPOL AIR HITAM,1.0,177,101,9,65,1,0,0,0,0,176,1,0
4,P.126 JELEBU,N03 SUNGAI LUI,UNDI AWAL 126/03/01,DEWAN PERDANA PULAPOL AIR HITAM,2.0,146,95,6,45,0,0,0,0,0,146,0,0